### ISSUE TITLE
this package is not supporting for angular 12

### ISSUE THREAD

**Issue by MustafaASK** [davidlj95/ngx#751]
### Project

ngx-meta

### What happened?

Error: node_modules/@davidlj95/ngx-meta/core/index.d.ts:4:10 - error TS2305: Module '"@angular/core"' has no exported member 'EnvironmentProviders'.

4 import { EnvironmentProviders, FactoryProvider, InjectionToken, ModuleWithProviders, Provider } from '@angular/core';

### Version

12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davidlj95** [comment]
Hi! This is the first issue in the library, thanks for contributing 😊 

Unfortunately the library [supports only the actively supported Angular versions](https://ngx-meta.dev/why/features/#compatibility-with-angular-actively-supported-versions). Right now being v16, v17 and v18. It also works with Angular v15 but it may stop working for that version too at some point.

I will anyways try to change the kind of providers so that it's compatible with even older versions than v15. Will try to get to v12.

Anyway it will be a one-off patch. The policy will remain to support only current [Angular actively supported versions](https://angular.dev/reference/releases#actively-supported-versions). Maintaining support for older versions is an extra maintenance burden I'd rather avoid.

Will let you know once there are updates on this

Thanks again

**Comment by davidlj95** [comment]
After giving it a try, I'm afraid I won't upload a patch for now to provide compatibility for older versions as it would imply getting rid of some APIs introduced to enhance standalone apps. Which is the preferred way to build Angular apps now. Those APIs are:

- **Environment provider APIs**: [`EnvironmentProviders`](https://v15.angular.io/api/core/EnvironmentProviders) and [`makeEnvironmentProviders`](https://v15.angular.io/api/core/makeEnvironmentProviders) introduced in Angular v15. [`ENVIRONMENT_INITIALIZER`](https://v14.angular.io/api/core/ENVIRONMENT_INITIALIZER) introduced in Angular v14. Those allow defining providers that can only be injected when creating an environment (like when a module was imported) and not in a `Component.providers` array.

Those could be replaced by some other APIs, for sure. But then would lose the benefits that those APIs provide. 

Another option would be maintaining two separate versions. One supporting newer APIs and another using older APIs to support older versions. But that is something I'd like to avoid as much as possible. As one of the main design principles of the library is to work seamlessly across latest Angular actively supported versions.

A third option could be to move the module based APIs apart. So they don't use the newer APIs under the hood and therefore are compatible with older versions of Angular. But it's not a straigth-forward change unfortunately

> Additionally docs and example apps infra [use the `satisfies` Typescript operator introduced in Typescript 4.9](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html) that isn't supported in Angular versions older than v15. In docs could introduce some notes here and there but in example apps would mean another layer of complexity in there too.

This is a trade-off anyway. If the community using the library prefers older versions support I'm open to change :)

Closing this for now
